### ISSUE TITLE
uap-core needs update

### ISSUE THREAD

**Issue by jace** [ua-parser/uap-python#100]
Snyk is flagging uap-python as insecure because it refers to an outdated version of uap-core with a known ReDoS vulnerability. The submodule needs to be updated. https://snyk.io/advisor/python/ua-parser#security

**Comment by abdelwahebmoalla** [comment]
is the project still maintained ?

**Comment by masklinn** [comment]
> is the project still maintained ?

Maybe. @elsigh has kindly accepted to give me write access to the repo, I've started updating a few things (e.g. restoring CI), I hope to release a 0.15 (with the matching update of -core) soon-ish.
