### ISSUE TITLE
Cache exception

### ISSUE THREAD

**Issue by nadav-levl** [ua-parser/uap-python#122]
Did anyone encounter this error?

```
   File "/usr/local/lib/python3.8/dist-packages/ua_parser/user_agent_parser.py", line 250, in Parse
     entry = _lookup(user_agent_string, jsParseBits)
   File "/usr/local/lib/python3.8/dist-packages/ua_parser/user_agent_parser.py", line 224, in _lookup
     entry = _PARSE_CACHE.get(key)
   TypeError: unhashable type: 'list'
```

**Comment by masklinn** [comment]
Hello, would it be possible for you to show how you're invoking `Parse`, and maybe print the parameters you're providing?

Given the way `_lookup` is constructed, the most likely issue is that you're passing a `list` as the user agent string (or as one of the keyword parameter values).

**Comment by nadav-levl** [comment]
It was running on a huge amount of data and happened from time to time so its a bit hard to investigate it.
anyway, maybe Parse should enforce casting to string. this is how I'm going to fix it for now.

**Comment by masklinn** [comment]
> It was running on a huge amount of data and happened from time to time so its a bit hard to investigate it. [...]  this is how I'm going to fix it for now.

If you're modifying the caller code to convert the input to string, it would probably make sense to log non-string inputs as well.

> maybe `Parse` should enforce casting to string

I don't think that makes much sense, and I'm not generally fond of "fuzzy" APIs.

Asserting that the input is a string, with a clear error message, would make sense. Though I don't know that it would help you much here.

**Comment by nadav-levl** [comment]
thx!
