### ISSUE TITLE
Improve uap-python installation instructions

### ISSUE THREAD

**Issue by Winterflower** [ua-parser/uap-python#14]
1. On Mac OS X Yosemite 
```make Makefile```
produces 
```make: Nothing to be done for `Makefile'.```

2. Running 
``` python setup.py install ``` 
seems to work, but importing the module fails with the error 
```
>>> from ua_parser import user_agent_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ua_parser/user_agent_parser.py", line 460, in <module>
    yamlFile = open(yamlPath)
IOError: [Errno 2] No such file or directory: 'ua_parser/regexes.yaml'
```

**Comment by pstrinkle** [comment]
This isn't a solution, but on ubuntu this is what I needed to do to get it past that:

 sudo pip uninstall pyyaml
 sudo apt-get install libyaml-0.2 libyaml-dev libpython2.7-dev
 sudo pip install pyyaml ua-parser user-agents

**Comment by Winterflower** [comment]
@pstrinkle thank you for the suggestion. I'll try to see if I can hack something similar together on Yosemite.

**Comment by mbarkhau** [comment]
Maybe it would be better if the distributed versions didn't require pyyaml. Why not just do a conversion to json when doing sdist and bdist_wheel?

I for one cannot get 0.5.0 installed from pypi, despite using a fresh virtualenv, and installing all the apt libraries mentioned above by pstrinkle.

**Comment by chrisbarry** [comment]
I'm also having the same trouble on osx..

**Comment by elsigh** [comment]
This should just be a PR not an issue. Closing - if someone wants to make a PR with more instructions that work that's cool with me.
