### ISSUE TITLE
UserAgentParser does not support patch_minor, but patch_minor is supported in uap-core

### ISSUE THREAD

**Issue by geoffblack** [ua-parser/uap-python#142]
The string 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36' should parse out to 
```
{
    'family': 'Chrome',
    'major': '41',
    'minor': '0',
    'patch': '2272',
    'patch_minor': '104'
}
```
but, instead, we get:
```
{
    'family': 'Chrome',
    'major': '41',
    'minor': '0',
    'patch': '2272'
}
```
User Agent `patch_minor` is already supported in uap-core; see https://github.com/ua-parser/uap-core/issues/22 and https://github.com/ua-parser/uap-core/pull/322/ for an example.

`UserAgentParser.Parse` and `_ParseUserAgent` should be updated to support User Agent `patch_minor`, as well.

**Comment by sanishmahadik** [comment]
Is there any update on this issue? We are also running into this problem when using the Python module. 🙇

**Comment by kevintelford-mck** [comment]
Same issue with missing `patch_minor`

**Comment by masklinn** [comment]
If somebody wants to contribute it, I don't mind merging it, but I won't be the one doing that: as I wrote on [ua-parser/uap-core#322#issuecomment-1118955704](https://github.com/ua-parser/uap-core/pull/322#issuecomment-1118955704) the thing doesn't seem to be finished or to have been adopted by any other implementation (not even the reference impl). As I also do not see its point, I do not care for it.

**Comment by geoffblack** [comment]
Thank you!
