### ISSUE TITLE
MS Edge support

### ISSUE THREAD

**Issue by jdalton** [ua-parser/uap-python#15]
Hey @elsigh!

So I got a report that [python-user-agents](https://github.com/selwin/python-user-agents) is detecting MS Edge wrong and after some digging it looks like it's using uap-python. I believe MS Edge detection was in  ua-parser but wanted to check. My python-fu is pretty weak so I'd need some assistance on that front.

**Comment by elsigh** [comment]
Can you drop a MS Edge UA string in here for testing? It should be that uap-python pulls uap-core with the right regexes.. but can test that theory.

**Comment by jdalton** [comment]
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by jdalton** [comment]
Any news?

**Comment by elsigh** [comment]
Sorry, haven't had a change to look at it..
But, someone else just filed:
https://github.com/ua-parser/uap-core/issues/78

**Comment by jdalton** [comment]
The pypi package was bumped.
