### ISSUE TITLE
Release 0.4.0 is a brown bag release. regexes.yaml is missing in egg

### ISSUE THREAD

**Issue by do3cc** [ua-parser/uap-python#16]
See also the file size on the pypi page for wheel and egg:
https://pypi.python.org/pypi/ua-parser

**Comment by elsigh** [comment]
This sounds like a problem insofar as some package is missing uap-core. As this library doesn't distribute an egg I think nothing is actually broken that warrants fixing.

That said, clearly there is a need for a maintainer to do packaging for the various python distro channels. Know anyone? ;)
