### ISSUE TITLE
[Question] Can we retrieve device type (e.g. desktop vs mobile)

### ISSUE THREAD

**Issue by mariana-s-fernandes** [ua-parser/uap-python#167]
Is it possible to return the device type, whether it's desktop or mobile? I can't find that in the parsing functions.

This [Snowplow enrichment](https://docs.snowplow.io/docs/enriching-your-data/available-enrichments/ua-parser-enrichment/) says to be using ua-parser and it has that info, so I was wondering if possible to get directly this package.

**Comment by masklinn** [comment]
> Is it possible to return the device type, whether it's desktop or mobile? I can't find that in the parsing functions.

Sadly that is not supported no, I assume snowplow maintains that mapping internally. uap-python is a frontend for the uap-core dataset, which does not currently include / expose this information.

You may want to subscribe to ua-parser/uap-core#534 which is basically this query in uap-core.
