### ISSUE TITLE
Investigate (and possibly add) `py.typed`

### ISSUE THREAD

**Issue by masklinn** [ua-parser/uap-python#218]
I'm not entirely clear on what it is but it comes up regularly so looks like it could be important.

resources:
- https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages
- https://github.com/python/typing/discussions/1429
- https://safjan.com/the-importance-of-adding-py-typed-file-to-your-typed-package/
- https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Comment by Daverball** [comment]
I'll save you the trouble: Yes, it is a required marker file for distributions that contain type hints: https://peps.python.org/pep-0561/#packaging-type-information
