### ISSUE TITLE
Pre-compile yaml into py file

### ISSUE THREAD

**Issue by mattrobenolt** [ua-parser/uap-python#23]
For context, see: https://github.com/getsentry/sentry/pull/1987

I notice this is being translated from yaml to json inside the sdist. Why not go one step further and generate the .py version instead?

tl;dr,

It takes 1.2 _seconds_ to import the module on my computer through parsing the yaml file and converting it at module import time, but 219 microseconds after it's compiled to a py file.

Before:
```
$ python -m timeit -s 'from sentry.utils.ua_parser import parser' 'reload(parser)'
10 loops, best of 3: 1.2 sec per loop
```

After:
```
$ python -m timeit -s 'from sentry.utils.ua_parser import parser' 'reload(parser)'
1000 loops, best of 3: 219 usec per loop
```

I can submit pull request for this if you're on board.

**Comment by elsigh** [comment]
I think the problem comes from distribution.. If you can make it optional to load a py file if present and then let folks compile if they want to I'm totally onboard.

**Comment by mattrobenolt** [comment]
You mean where someone may supply their own yaml file of patterns?

**Comment by elsigh** [comment]
That's how this lib works - it depends on `uap-core` which is the project that contains the regexes yaml file.

**Comment by mattrobenolt** [comment]
Yeah, I understand that.

What I'm suggesting is, we're already taking this list of yaml files that come in from `uap-core`, and converting them into `json` inside `sdist`. We could take that one step further and just compile down into `py` files instead.

**Comment by elsigh** [comment]
I have no objections to making things faster =)

**Comment by mattrobenolt** [comment]
Step 1: #27 :)
