### ISSUE TITLE
ua-parser indirectly requires itself

### ISSUE THREAD

**Issue by lexdene** [ua-parser/uap-python#246]
One of the internal systems of the department I'm working in prohibits cyclic dependencies of any kind.
So I cannot install the latest version of `ua-parser` there.

    root@0a4fff0b62e5:~# pip install -q ua-parser pipdeptree
    root@0a4fff0b62e5:~# pip freeze
    packaging==24.2
    pipdeptree==2.24.0
    ua-parser==1.0.0
    ua-parser-builtins==0.18.0
    root@0a4fff0b62e5:~# pipdeptree -p ua-parser
    Warning!!! Cyclic dependencies found:
    * ua-parser-builtins => ua-parser => ua-parser-builtins
    * ua-parser => ua-parser-builtins => ua-parser
    ------------------------------------------------------------------------

**Comment by masklinn** [comment]
That's an interesting issue, I'm not too sure how to change it as they do depend on one another.

I guess I could always remove the dependency of `ua-parser-builtins` on `ua-parser` and it would just be broken if you install it on its own, something which there is no reason whatsoever to do?

**Comment by lexdene** [comment]
I temporarily fix by installing an old version `pip install "ua-parser<1"`.
So it is not urgent.

**Comment by masklinn** [comment]
I published post releases for all the stables to remove the dependency from the builtins to the main package (I don't think it's possible for prereleases but I assume you don't use that). So there should be no circular dependency anymore.

**Comment by lexdene** [comment]
Now I can install the latest version ua-parser 1.0.0.
Thank you so much :heart: .
