### ISSUE TITLE
Cut a 0.5.1 release

### ISSUE THREAD

**Issue by pmclanahan** [ua-parser/uap-python#34]
I need to use the changes from #28, but can't just pip install the tarball from github due to those not including the submodule. I'd really appreciate a PyPI release.

**Comment by owocki** [comment]
+1 on a 0.5.1 release.  we'd like one too!

**Comment by mattrobenolt** [comment]
I'm just waiting on getting permission for pypi, and I'll happily do this. :)

**Comment by pmclanahan** [comment]
Thanks a lot @mattrobenolt :cake:

**Comment by glogiotatidis** [comment]
+1 on that. Thanks!

**Comment by zaabjuda** [comment]
+1 on that. Thanks!

**Comment by nass600** [comment]
+1. Thanks for the effort

**Comment by mattrobenolt** [comment]
This has been resolved.
