### ISSUE TITLE
AWS Redshift UDF Installation

### ISSUE THREAD

**Issue by destinymedia** [ua-parser/uap-python#40]
Hi Guys,

In November 2015 AWS Redshift added Python support for User Define Functions. I am new to Python but would like to add this library to Redshift but could use some guidance as to how. This could become an alternative setup script for others. According to the following link, AWS requires the source in a zip file and added to an S3 bucket. 

http://docs.aws.amazon.com/redshift/latest/dg/udf-python-language-support.html

Once prepared the library can be created then functions can be created based on the library. As best I can tell, UAP has a core that requires pre-processing. Any suggestions on how to write an alternative setup script for the Python project to include all of that in a zip?

**Comment by mattrobenolt** [comment]
I don't know anything about this, but the wheel file that gets published to pypi is a .whl file. This is literally a zip file and can be uncompressed with just `unzip`. Is that enough?

**Comment by mattrobenolt** [comment]
Either way, the distributions pushed to pypi have a compiled version of uap-core included. With 0.6.x, there's an included _regexes.py file which doesn't need anything else from uap-core. So if you need to repackage, you could download either the whl or tar.gz from pypi and repackage into whatever format you need.

**Comment by destinymedia** [comment]
Thank you Matt. It requires the py source files including the _regexes.py in the root of a zip file and I found files in the packages folder after installing by pip. I'll give that a go and see if that works.

**Comment by mattrobenolt** [comment]
Yep, the distribution includes everything and has 0 dependencies outside of what's included. 

For some context, this all happens inside our setup.py when we run sdist, etc. so you could technically build your own, but not really valuable since I publish the correct package already built. :)

I'm going to close this now unless there's something else we'd need to do.
