### ISSUE TITLE
Unrecognised User-Agents

### ISSUE THREAD

**Issue by Kilte** [ua-parser/uap-python#43]
## Windows Live Mail

string: `Outlook-Express/7.0 (MSIE 7.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; TmstmpExt)`
actual: `{'family': 'IE', 'major': '7', 'minor': '0', 'patch': None}`

string: `Outlook-Express/7.0 (MSIE 7.0; Windows NT 5.1; Trident/4.0; AskTB5.6; TmstmpExt)`
actual: `{'family': 'IE', 'major': '7', 'minor': '0', 'patch': None}`

string: `Outlook-Express/7.0 (MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; Media Center PC 6.0; OfficeLiveConnector.1.4; OfficeLivePatch.1.3; InfoPath.3; FDM; TmstmpExt)`
actual: `{'family': 'IE', 'major': '7', 'minor': '0', 'patch': None}`

string: `Outlook-Express/7.0 (MSIE 6.0; Windows NT 5.1; SV1; GTB6.3; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; InfoPath.2; .NET CLR 3.0.04506.648; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; OfficeLiveConnector.1.3; OfficeLivePatch.0.0; TmstmpExt)`
actual: `{'family': 'IE', 'major': '6', 'minor': '0', 'patch': None}`

string: `Outlook-Express/7.0 (MSIE 8; Windows NT 5.1; Trident/4.0; GTB7.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; TmstmpExt)`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`

string: 'Outlook-Express/7.0 (MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; InfoPath.1; TmstmpExt)',
actual: `{'family': 'IE', 'major': '8', 'minor': '0', 'patch': None}`

string: `Outlook-Express/7.0 (MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; HPDTDF; .NET4.0C; BRI/2; AskTbLOL/5.12.5.17640; TmstmpExt)`
actual: `{'family': 'IE', 'major': '9', 'minor': '0', 'patch': None}`

expected: `{'family': 'Windows Live Mail', 'major': None, 'minor': None, 'patch': None}`
(for all user-agents above, not sure about a version)

## Microsoft Outlook

string: `Microsoft Office/12.0 (Windows NT 6.1; Microsoft Office Outlook 12.0.6739; Pro)`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Outlook', 'major': '2007', 'minor': None, 'patch': None}`

string: `Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.5128; Pro)`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Outlook', 'major': '2010', 'minor': None, 'patch': None}`

string: `Microsoft Office/16.0 (Microsoft Outlook Mail 16.0.6525; Pro)`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Outlook', 'major': '2016', 'minor': None, 'patch': None}`

string: `Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.6326; Pro)`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Outlook', 'major': '2016', 'minor': None, 'patch': None}`

string: `Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Microsoft Outlook 16.0.6366; ms-office; MSOffice 16)`
actual: `{'family': 'IE', 'major': '7', 'minor': '0', 'patch': None}`
expected: `{'family': 'Outlook', 'major': '2016', 'minor': None, 'patch': None}`

## Other

string: `Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.2pre) Gecko/2009031117 Spicebird/0.7.1`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Spicebird', 'major': '0', 'minor': '7', 'patch': '1'}`

string: `Mozilla/5.0 (Windows NT 10.0; rv:38.0) Gecko/20100101 Thunderbird/38.5.1 Lightning/4.0.5.1`
actual: `{'family': 'Lightning', 'major': '4', 'minor': '0', 'patch': '5'}`
expected: `{'family': 'Thunderbird', 'major': '38', 'minor': '5', 'patch': '1'}`

string: `Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.9pre) Gecko/20100209 Shredder/3.0.2pre`
actual: `{'family': 'Other', 'major': None, 'minor': None, 'patch': None}`
expected: `{'family': 'Shredder', 'major': '3', 'minor': '0', 'patch': '2pre'}`

string: `Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.9pre) Gecko/20100308 Lightning/1.0b1 Shredder/3.0.4pre`
actual: `{'family': 'Lightning', 'major': '1', 'minor': '0', 'patch': 'b1'}`
expected: `{'family': 'Shredder', 'major': '3', 'minor': '0', 'patch': '4pre'}`

**Comment by elsigh** [comment]
Ideally, just create a pull request for `uap-core` that fixes these. In general, at this point, when people want fixes it's better to figure out how to fix them and create a pull with tests than to submit an issue (it will otherwise, most likely, never get tackled)
