### ISSUE TITLE
Add Brave browser support

### ISSUE THREAD

**Issue by swarnava** [ua-parser/uap-python#44]
Sample Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.7.11 Chrome/47.0.2526.110 Brave/0.36.5 Safari/537.36

website: https://brave.com

**Comment by mattrobenolt** [comment]
This needs to be added into `uap-core` since we just source rules from there: https://github.com/ua-parser/uap-core

**Comment by swarnava** [comment]
https://github.com/ua-parser/uap-core/issues/128

**Comment by swarnava** [comment]
can we start work now?
