### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by adamchainz** [ua-parser/uap-python#46]
Upgrading from 0.4.0 to 0.7.1 I was surprised to find everything coming back in `bytes` rather than `str`, I would have found this out more easily with a changelog to read 😄

**Comment by mattrobenolt** [comment]
```
>>> str is bytes
True
>>> bytes
<type 'str'>
```

What's the issue? `bytes` is just an alias for `str`.

**Comment by adamchainz** [comment]
Only on Python 2

```
$ python3
>>> str
<class 'str'>
>>> bytes
<class 'bytes'>
```

**Comment by adamchainz** [comment]
8621957e3bca57d550cf3631d4a38930e17eed50 changed things into `bytes` afaict

**Comment by mattrobenolt** [comment]
That should be unrelated. That's just for the generated `_regexes.py` file on disk, needs to be bytes. Unrelated to the output from the library.

Can you give me an example of which changed?

**Comment by adamchainz** [comment]
On Python 2...

Version 0.4.0

```
In [3]: user_agent_parser.Parse('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36')
Out[3]:
{'device': {'brand': None, 'family': 'Other', 'model': None},
 'os': {'family': u'Mac OS X',
  'major': u'10',
  'minor': u'9',
  'patch': u'4',
  'patch_minor': None},
 'string': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36',
 'user_agent': {'family': u'Chrome',
  'major': u'41',
  'minor': u'0',
  'patch': u'2272'}}
```

Version 0.7.1

```
In [6]: user_agent_parser.Parse('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36')
Out[6]:
{'device': {'brand': None, 'family': 'Other', 'model': None},
 'os': {'family': 'Mac OS X',
  'major': u'10',
  'minor': u'9',
  'patch': u'4',
  'patch_minor': None},
 'string': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36',
 'user_agent': {'family': u'Chrome',
  'major': u'41',
  'minor': u'0',
  'patch': u'2272'}}
```

There is `u` prefix on `os['Family']` any more, i.e. it has gone from `unicode`/`str` to `str`/`bytes`. Actually now I look at it, this is the only example there, though I can't tell for the `None` fields. I fixed it in my application code with a blanket `if isinstance(x, str): x = x.decode('utf-8')` (application code is Python 2 despite my initial reporting in Python 3 speak for `str`/`bytes`, just to confuse you).

**Comment by samuelcolvin** [comment]
changelog would be very useful. I'm just doing some detective work to find out what changed on `0.7.3`...

**Comment by mattrobenolt** [comment]
Generally things don't change. Mostly it's just bumping the definitions for `uap-core`.

You can always use GitHub's fancy compare view: https://github.com/ua-parser/uap-python/compare/0.7.2...0.7.3

**Comment by elsigh** [comment]
just closing cuz old
