### ISSUE TITLE
Wrong Android Browser

### ISSUE THREAD

**Issue by shaunpatterson** [ua-parser/uap-python#48]
`Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; HTC_IncredibleS_S710e Build/GRJ90) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

Returns:
`{'user_agent': {'family': 'Android', 'major': '2', 'minor': '3', 'patch': '5'}, 'device': {'family': 'HTC IncredibleS S710e', 'brand': 'HTC', 'model': 'IncredibleS S710e'}, 'os': {'family': 'Android', 'major': '2', 'patch_minor': None, 'minor': '3', 'patch': '5'}, 'string': 'Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; HTC_IncredibleS_S710e Build/GRJ90) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1'}`

http://www.useragentstring.com/index.php marks the browser as "4.0" but here it's 2.3.5, which is the android version, not the browser version

**Comment by mattrobenolt** [comment]
This still seems to be wrong according to you against the latest version. Do you mind opening this up against [ua-parser/uap-core](https://github.com/ua-parser/uap-core/issues/new)? There's nothing we can do here since we source the rules from there.
