### ISSUE TITLE
Process for updating uap-core?

### ISSUE THREAD

**Issue by asalant** [ua-parser/uap-python#51]
I'm wondering what's the process for updating `uap-python` with the latest rules from `uap-core`?It looks like @mattrobenolt usually does this - do you want update requests as an issue like this, a PR to merge?

The git submodule for `uap-core` currently points at a commit not associated with a tag in `uap-core` which suggests that we don't need to wait for a "release" from `uap-core` to update `uap-python`. Seems like it would be preferable to point at a release but makes sense that we'd want to avoid that level of coordination.

I'm asking because I recently submitted https://github.com/ua-parser/uap-core/pull/216 that was merged to master over the weekend and would like to pull it into `uap-python` so I can use it. 

Would be helpful to update the README with instructions on how to make these updates.

Thanks!

**Comment by mattrobenolt** [comment]
It's just a matter of bumping the submodule version and confirming that tests still pass. I can do this today. Other than that, there's no schedule or policy around doing this. I just do it when I personally want updated rules or someone bugs me. :)

**Comment by asalant** [comment]
Thanks!

**Comment by asalant** [comment]
Checking in this release. Thanks.

**Comment by asalant** [comment]
Here's a PR if that helps: https://github.com/ua-parser/uap-python/pull/52

**Comment by asalant** [comment]
Another ping on this request to release a new version. Passing PR at https://github.com/ua-parser/uap-python/pull/52.

**Comment by asalant** [comment]
@mattrobenolt - calling you out by name in case you are not seeing my comments. Appreciate your help releasing this. Thanks.

**Comment by mattrobenolt** [comment]
I have published 0.7.3 with latest uap-core.

**Comment by asalant** [comment]
Thanks!
