### ISSUE TITLE
uap-core should be kept upto date better.

### ISSUE THREAD

**Issue by freshteapot** [ua-parser/uap-python#6]
The sub-module hash for uap-core comes from November.

- Can we get an update to 'pip' with the latest regexes from 'uap-core?

For those of you who are interested. If you have ua-parser and you want to get the latest regexs. You will need to run the 'makefile' or 'python setup.py sdist'.

The reason for this, you need the 'json' files as well as the 'yaml'.
```
git clone https://github.com/ua-parser/uap-python
cd uap-python
git submodule update --init
python setup.py sdist
```
Then check 'regexes.yaml' for an item in the latest copy. For me, that was 'Opera Coast'. A driving reason why I wanted to update my ua-parser.

**Comment by mbarkhau** [comment]
Indeed. Microsoft Edge isn't detected as it currently stands.

**Comment by mattrobenolt** [comment]
:+1:

**Comment by elsigh** [comment]
This is why submodules suck - you can't pin them to head. Maybe we could switch to subtree? 

That said, @freshteapot : how about a PR to update uap-python to the latest commit?

**Comment by elsigh** [comment]
Ok, @selwin updated today to the latest uap-core. 
I think it would be the best situation if this repo somehow pulled/pushed on green with HEAD at uap-core, but I don't know anyone keen to write the system to do that.

**Comment by elsigh** [comment]
I'm going to close this issue as it's just a bump request.
