### ISSUE TITLE
Browser family error?

### ISSUE THREAD

**Issue by sursu** [ua-parser/uap-python#61]
Take the following User Agent instance:
`'Mozilla/5.0 (Linux; Android 5.0.2; SM-T535 Build/LRX22G; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Safari/537.36 [FB_IAB/FB4A;FBAV/77.0.0.20.66;]'`

Place that in a variable `ua`, then:

`user_agent_parser.ParseUserAgent(ua)`

says that the browser family is 'Facebook'. 

I have never heard of such a browser family.

Is this behavior correct?

**Comment by zrothberg** [comment]
just scrolling through and saw this
it means its on the facebook apps internal browser
