### ISSUE TITLE
Repository lacks license

### ISSUE THREAD

**Issue by scarabeusiv** [ua-parser/uap-python#63]
As per $SUBJ the pypi sdist tarball does not contain license file nor the repository.

Even if you forked you still need to ship a license file (in this case I guess Apache-2.0) within the repo and the archive.

**Comment by mattrobenolt** [comment]
Is this not sufficient? https://github.com/ua-parser/uap-python/blob/master/ua_parser/LICENSE

**Comment by mattrobenolt** [comment]
Pretty sure it is with https://github.com/ua-parser/uap-python/pull/58
