### ISSUE TITLE
Problem of parsing Edge's user-agent

### ISSUE THREAD

**Issue by Harpsichord1207** [ua-parser/uap-python#64]
A user-agent of Edge is 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
```
 The parsed result of browser version is `{'major': 15, 'minor':15063}`, and I parsed the same ua in the following website [whatismybrowser](https://developers.whatismybrowser.com/useragents/parse/#parse-useragent), it returnd `Edge 40`， and I found that 15 is the Layout Engine Version and 40 is Software Version, maybe return Software Version is better.
Forgive my poor English and thanks to the contribution

**Comment by elsigh** [comment]
this is a uap-core issue, and I think irrelevant now
