### ISSUE TITLE
Incorrect Parsing for Keyword HTTP

### ISSUE THREAD

**Issue by pkqxdd** [ua-parser/uap-python#67]
When parsing UA string of `HTTPie/0.9.9`, `user_agent_parser` reports it as a "Generic Feature Phone", even though it's obviously not a phone.

**Comment by mattrobenolt** [comment]
This isn't an issue with this repository, I'd suggest opening an issue with [uap-core](https://github.com/ua-parser/uap-core) since that's where all the rules come from.
