### ISSUE TITLE
uap-core pointing to 10 month old commit

### ISSUE THREAD

**Issue by SrdjanNikitovic** [ua-parser/uap-python#68]
Hello there.

We have a problem that new user agents are not parsed correctly in Python.
After looking investigating the regexes.yaml file, we see that Python library is pointing to a 10 month old commit of uap-core, but the most recent version of uap-core is 10 days old.

Is there a reason why old uap-core is used, or we can use the new one?

**Comment by polischouckserg** [comment]
Hi @SrdjanNikitovic, we have forked this repo and updated uap-core [here](https://github.com/admitad-github/uap-python/commit/16b7615619786a9428b2ac0e55f5d0f23bdd63d2). You can do the same or use our fork.

Related [issue](https://github.com/ua-parser/uap-python/issues/66).

**Comment by polischouckserg** [comment]
#66

**Comment by sjzabel** [comment]
https://github.com/soon/uap-python-next it looks like this project/package may have done the same

**Comment by mattrobenolt** [comment]
Good to see that @soon attempted to contribute back the changes needed. I stopped bumping commits from uap-core because tests started to break, and I don't have the bandwidth or capacity to fix them. Bumping versions is trivial and I was doing them regularly until it started to break tests.

**Comment by polischouckserg** [comment]
@mattrobenolt there is PR #70 with fixed tests and updated uap-core and it's waiting to be merged.

**Comment by Matt343** [comment]
Now that the PR has been merged, what do we need to do to get a release created and pushed to pypi?

**Comment by admitad-github** [comment]
Only maintainers have rights to create a release and push it to the PyPI.
@mattrobenolt @selwin can you please do this?

**Comment by mattrobenolt** [comment]
I’ll take a look at this today and see what’s involved at this point. I’ll try to get a release tagged and uploaded today.

**Comment by yesthisisjoe** [comment]
Any updates making a new PyPl release? There is a key uap-core fix that my team would be interested in receiving via the update.

**Comment by Maggers** [comment]
Thanks @mattrobenolt - I'm on the Edge engineering team (Chromium based Edge) and we're watching this update closely too as it's impacting users of our Canary, Dev and Beta channels. Would love to see this tagged and uploaded for downstream adoption. Thanks! - Jason

**Comment by soon** [comment]
Just FYI for everyone waiting for pypi release: I've forked this repo a while ago and deployed to pypi: https://pypi.org/project/ua-parser-next/. It contains the most recent changes from uap-core, passes all tests and allows to pass custom device parses in case if uap-core is not currently supporting them (I needed to parse a new samsung device). The package was renamed to `ua_parser_next` in order not to conflict with base `ua_parser` package, all other functions are the same. I'm currently using it in several projects, so if you need the most recent features from uap-core you can try ua-parser-next

**Comment by elsigh** [comment]
@soon I would be happy to make you a maintainer/dev on this repo and then you could update from here? I'm a maintainer but don't depend on or use this repo so..

**Comment by elsigh** [comment]
Also since I merged #79 I think this particular issue is now moot (but not the overall/future issues)

**Comment by soon** [comment]
@elsigh Thank you, will be happy to help

**Comment by einhorntee** [comment]
@soon sorry to bother you, but do you know when you'll be able to release the new version?
If you don't have the resources in the next couple of weeks, I'd be happy to help out as well.

**Comment by soon** [comment]
@einhorntee I don't have access to this repo and I'm unable to release it. But I just checked, my fork (https://github.com/soon/uap-python-next) points to the latest commit in master in uap-core. So if switching to fork is an option you can try it

**Comment by mattrobenolt** [comment]
I have pushed 0.9.0.

https://pypi.org/project/ua-parser/0.9.0/
