### ISSUE TITLE
Slowness in parsing user agent

### ISSUE THREAD

**Issue by bt-wil** [ua-parser/uap-python#71]
Some user agent strings are causing the user agent parser to be really slow.

```
from ua_parser import user_agent_parser

ua_str = "Mozilla/5.0 (iPhone; CPU iPhone OS 7_5 like Mac OS X) AppleWebKit/1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890 (KHTML, like Gecko) Version/5.1 Mobile/9334 Safari/7548.320"

s = time.time()
print(user_agent_parser.ParseUserAgent(ua_str))
print('took ', time.time() - s)
```

* v0.7.3 took ~0.05s
* v0.8.0 took ~7.0s
* v0.8.0 took ~110s! with `AppleWebKit/<400 digits>`

The notable change was updating `uap-core` gitsubmodule from `ce89c7637eeeb07b3464dbf40645bb3973723c0a` to `fc570f378e41063bad3bdf0532967743efc75b4b`

After digging around, I've found that the issue is due to the regex addition in `uap-core`:
* https://github.com/ua-parser/uap-core/blob/89d333eeedc61f0e81c2a60ebb867613c43b0abd/regexes.yaml#L12

The latest regexes.xml altered the regex, and looks to have fixed the slowness issue.
* https://github.com/ua-parser/uap-core/blob/bf80eb25f940f2c2a4672681d753a8034839066c/regexes.yaml#L12

PR for https://github.com/ua-parser/uap-python/pull/70 looks to use the new regex which helps the issue.

**Comment by elsigh** [comment]
maybe this is fixed now?
