### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by heyman** [ua-parser/uap-python#82]
Thanks for a useful library!

I noticed that a lot has happened in this repo since the last PyPI release (april 2018). Would it be possible to cut a new PyPI release?

**Comment by karls** [comment]
I left a comment on an issue for `selwin/python-user-agents`, which uses this library: https://github.com/selwin/python-user-agents/issues/92#issuecomment-579740728.

**Comment by mattrobenolt** [comment]
I have pushed 0.9.0. https://pypi.org/project/ua-parser/0.9.0/

**Comment by karls** [comment]
Super! Thanks @mattrobenolt!
