### ISSUE TITLE
uap-python does not parse current apple phone information from ua strings

### ISSUE THREAD

**Issue by OdifYltsaeb** [ua-parser/uap-python#89]
```
z = user_agent_parser.ParseDevice('Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/70.0.3538.75 Mobile/15E148 Safari/605.1')
print(z)
{'family': 'iPhone', 'brand': 'Apple', 'model': 'iPhone'}
```
Even though the information is there, the exact model is not picked up, unfortunately. 

Thank you for the work you've put into this project btw :)

**Comment by masklinn** [comment]
Hello Alan, sorry for the delay in looking at your issue.

I... don't think the exact model is available in the UA string? Nothing jumps out to me helping there, and ["competitors"](https://developers.whatismybrowser.com/useragents/parse/) don't seem to see any more information.

Either way, if it were possible to get more precise hardware information from this UAS (which again I don't see), this would probably be an issue to submit to [ua-parser/uap-core](https://github.com/ua-parser/uap-core) as that's the project which handles the actual data and corresponding parsing tests. So first the test case (and possibly probably new rules) would have to be pushed over there, then the data updated in uap-python, and then possibly in case of a parsing error on this side that fixed.

**Comment by OdifYltsaeb** [comment]
Hehe :) Thank you for the reply. It's been a while since I worked on that project. I kind of thought that based on the OS version, you could also guess the model - i think

**Comment by masklinn** [comment]
> Hehe :) Thank you for the reply. It's been a while since I worked on that project. I kind of thought that based on the OS version, you could also guess the model - i think

I wouldn't think so. iOS 12 was installable on all phones from the 5S to the XR, so at best you could say "it's any of those 14 models" but... that's no more information than "iOS 12" gives you in the first place.

**Comment by OdifYltsaeb** [comment]
Right. Perhaps that's then something we should have fixed the other way around then.

Back then, we used your project as a part of the data gathering & fingerprinting app. We actually had the screen size and other information about the devices too. Guess we should have combined everything, and then we probably would have been able to provide better information. Anyway - that ship sailed a long time ago.

I think we can close this ticket.

**Comment by masklinn** [comment]
> Back then, we used your project as a part of the data gathering & fingerprinting app. We actually had the screen size and other information about the devices too. Guess we should have combined everything, and then we probably would have been able to provide better information.

Yeah that sounds like it could have provided better precision with respect to devices, screen size would have done a bit and depending on the additional info you might have been able to pinpoint devices a lot more, at least for apple ones.

> I think we can close this ticket.

Sorry I couldn't help.
