### ISSUE TITLE
Case insensitive parsing

### ISSUE THREAD

**Issue by chapinb** [ua-parser/uap-python#90]
Thank you for this great utility! I wanted to share some feedback and offer to take on the contribution to work on it if you're open to that.

I did a quick search of prior issues and didn't see anything related. Please feel free to link if it is a duplicate

I recently found that lower case user agent strings led to issues where data was not extracted/parsed properly. The below illustrates this:

```python
>>> from ua_parser import user_agent_parser
>>> import pprint
>>> ua_string = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36'
>>> normal_case_parsed = user_agent_parser.Parse(ua_string)
>>> pprint.pprint(normal_case_parsed)
{'device': {'brand': 'Apple', 'family': 'Mac', 'model': 'Mac'},
 'os': {'family': 'Mac OS X',
        'major': '10',
        'minor': '9',
        'patch': '4',
        'patch_minor': None},
 'string': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 '
           '(KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36',
 'user_agent': {'family': 'Chrome',
                'major': '41',
                'minor': '0',
                'patch': '2272'}}
>>> lower_case_parsed = user_agent_parser.Parse(ua_string.lower())
>>> pprint.pprint(lower_case_parsed)
{'device': {'brand': None, 'family': 'Other', 'model': None},
 'os': {'family': 'Other',
        'major': None,
        'minor': None,
        'patch': None,
        'patch_minor': None},
 'string': 'mozilla/5.0 (macintosh; intel mac os x 10_9_4) applewebkit/537.36 '
           '(khtml, like gecko) chrome/41.0.2272.104 safari/537.36',
 'user_agent': {'family': 'Other', 'major': None, 'minor': None, 'patch': None}}
```

Let me know of any other details to provide, otherwise I will take a look for where a patch could be applied and see if I can contribute one.

**Comment by mattrobenolt** [comment]
I would definitely argue this is related to https://github.com/ua-parser/uap-core itself. I don't know if this is even valid to assume a lowercase useragent is the same as one that isn't.

What case are you lowercasing these in the first place or why are they lowercased?

I'm going to close this issue since it definitely wouldn't apply here. We just use patterns from uap-core, and the patterns would been to be made case insensitive or whatever. I'm just not sure if that's even valid.

**Comment by chapinb** [comment]
Thanks for the quick response! The use case here is that we have the web server log data ship in to Elasticsearch, which is processing the data in a case insensitive manner. We then query against the stored log data, parse it using this library, then supplement the existing records with the extracted attributes. I was able to resolve this issue by using the title case method on the user agent strings.
